/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/celestiaorg/celestia-app/v10/pkg/rsema1d/cshim */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 25 "cshim.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "cshim_da.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "cshim_full.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int rsema1d_commit(uint32_t k, uint32_t n, unsigned char* rows, size_t rowLen, size_t numRows, unsigned char* outCommitment, uint64_t* outHandle);
extern int rsema1d_open_at(uint64_t handle, uint32_t rangeStart, uint32_t rangeLen, unsigned char* point, size_t pointLen, uint32_t sampleCount, unsigned char** outProof, size_t* outProofLen);
extern int rsema1d_verify_at(uint32_t k, uint32_t n, unsigned char* commitment, unsigned char* proof, size_t proofLen, unsigned char* point, size_t pointLen, unsigned char* outValue);
extern void rsema1d_free_handle(uint64_t handle);
extern void rsema1d_free_buf(unsigned char* buf);
extern uint64_t rsema1d_encode_call_count(void);
extern int rsema1d_encode_extended(uint32_t k, uint32_t n, unsigned char* rows, size_t rowLen, size_t numRows, unsigned char* outCommitment, unsigned char** outExtended, size_t* outExtendedLen);
extern int rsema1d_load_extended(unsigned char* extended, size_t extendedLen, unsigned char* outCommitment, uint64_t* outHandle);
extern int rsema1d_open_at_full(uint64_t handle, uint32_t rangeStart, uint32_t rangeLen, unsigned char* rcol, size_t rcolLen, unsigned char* rrow, size_t rrowLen, uint32_t sampleCount, unsigned char** outProof, size_t* outProofLen);
extern int rsema1d_verify_at_full(uint32_t k, uint32_t n, unsigned char* commitment, unsigned char* proof, size_t proofLen, unsigned char* rcol, size_t rcolLen, unsigned char* rrow, size_t rrowLen, unsigned char* outValue);

#ifdef __cplusplus
}
#endif
