//! Cross-validation reference for the Go `EncodeGKRInputSquare`
//! (pkg/rsema1d/gkr_square.go).
//!
//! For a set of DETERMINISTIC inputs it builds the exact `MultiLinearPoly<GF2x8>`
//! that the Go side reconstructs from `inputVals`, runs the real
//! `install_da_commitment` (the same `build_rows` + Go rsema1d encode the GKR
//! prover commits to), and prints each input's commitment root hex. The Go test
//! `pkg/rsema1d/gkr_square_test.go` bakes these roots in as expected constants
//! and asserts byte-equality.
//!
//! The input byte vectors are generated by `gen_input` below; the IDENTICAL
//! generator is reproduced in the Go test so both sides consume the same
//! `inputVals`. `inputVals[i]` is the GF2x8 element for hypercube index i, with
//! bit s = SIMD lane s (matching `GF2x8::unpack`).
//!
//! Run:
//!   cd rust && PATH=/opt/homebrew/bin:$PATH MPI_HOME=/opt/homebrew/opt/open-mpi \
//!     DYLD_LIBRARY_PATH=$PWD/crates/rsema1d-sys/lib \
//!     OMPI_MCA_rmaps_base_oversubscribe=1 CARGO_NET_GIT_FETCH_WITH_CLI=true \
//!     cargo +nightly-2025-05-17 test -p rsema1d-pcs --release gkr_square -- --nocapture

use gf2::GF2x8;
use polynomials::MultiLinearPoly;
use rsema1d_pcs::install_da_commitment;

/// Kinds of deterministic input. Must match the Go test's generator exactly.
#[derive(Clone, Copy)]
enum Kind {
    Zeros,
    Ones,
    /// inputVals[i] = ((i*mul + add) & 0xFF) as u8
    Pattern { mul: usize, add: usize },
}

/// Deterministic input generator, byte-identical to the Go `genInput`.
fn gen_input(num_vars: usize, kind: Kind) -> Vec<u8> {
    let len = 1usize << num_vars;
    (0..len)
        .map(|i| match kind {
            Kind::Zeros => 0u8,
            Kind::Ones => 0xFFu8,
            Kind::Pattern { mul, add } => (i.wrapping_mul(mul).wrapping_add(add) & 0xFF) as u8,
        })
        .collect()
}

fn root_hex(num_vars: usize, kind: Kind) -> String {
    let input = gen_input(num_vars, kind);
    // Build the MultiLinearPoly<GF2x8> whose hypercube_basis is exactly the
    // GF2x8 vector Go's EncodeGKRInputSquare reconstructs from inputVals.
    let coeffs: Vec<GF2x8> = input.iter().map(|&b| GF2x8 { v: b }).collect();
    let poly = MultiLinearPoly::new(coeffs);
    let root = install_da_commitment(num_vars, &poly);
    hex_lower(&root)
}

fn hex_lower(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{:02x}", b));
    }
    s
}

#[test]
fn gkr_square_roots() {
    // (label, num_vars, kind) — the Go test uses the IDENTICAL list.
    let cases: &[(&str, usize, Kind)] = &[
        ("nv8_zeros", 8, Kind::Zeros),
        ("nv8_ones", 8, Kind::Ones),
        ("nv8_patA", 8, Kind::Pattern { mul: 37, add: 11 }),
        ("nv10_patB", 10, Kind::Pattern { mul: 89, add: 5 }),
        ("nv11_patC", 11, Kind::Pattern { mul: 197, add: 3 }),
        ("nv12_patD", 12, Kind::Pattern { mul: 7, add: 123 }),
    ];

    println!("=== GKR square commitment roots (Rust reference) ===");
    for (label, nv, kind) in cases {
        let root = root_hex(*nv, *kind);
        println!("{label} num_vars={nv} root={root}");
    }
    println!("=== end ===");
}
